#!/bin/sh

# set root pointer

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

# panel
# tint2 &

# set some bsp specific

xbacklight -set 30 &
polybar example -c ~/.config/polybar/config.ini &


###BSPWM RULES###
bspc monitor -d 1 2 3 4 5 6 7
bspc config border_width         3
bspc config window_gap           15 
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding 	 20 
bspc config focused_border_color "#e8a2af"
bspc config normal_border_color "#b5e8e0" 
bspc rule -a Zathura state tiled
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action2 resize_corner
###OTHER SETTINGS & AUTOSTART###
$HOME/.config/bspwm/autostart.sh
